/* Seed content transcribed from the design mockup.
   Everything here is editable from the admin panel once wired. */

import type { Category, Faq, Product, Review, SiteSettings } from "./types";

const now = "2026-10-09T10:00:00.000Z";

export const seedCategories: Category[] = [
  { id: "cat-3seater", slug: "3-seater-sofas", name: "3 seater sofas", type: "three", fabric: "#D8CBB4", bg: "#EFE8DC", blurb: "The classic family sofa — room for three, built for every day." },
  { id: "cat-corner", slug: "corner-sofas", name: "Corner sofas", type: "corner", fabric: "#5E7A6B", bg: "#DCE5DA", blurb: "L-shaped comfort that anchors the whole living room." },
  { id: "cat-32sets", slug: "3-plus-2-sets", name: "3+2 sets", type: "three", fabric: "#8C6B57", bg: "#F1E4D9", blurb: "A matching 3 seater and 2 seater — seating for five." },
  { id: "cat-armchairs", slug: "armchairs", name: "Armchairs", type: "chair", fabric: "#C27B5A", bg: "#F4E1D6", blurb: "One perfect seat, made for reading, naps and quiet corners." },
  { id: "cat-recliners", slug: "recliners", name: "Recliners", type: "chair", fabric: "#3F4443", bg: "#E8DFD2", blurb: "Kick back properly — smooth recline, deep cushioning." },
  { id: "cat-sofabeds", slug: "sofa-beds", name: "Sofa beds", type: "sofa-bed", fabric: "#2E3F5C", bg: "#DCE8F3", blurb: "A proper sofa by day, a comfortable bed by night." },
];

export const seedProducts: Product[] = [
  {
    id: "prod-oslo-3",
    slug: "oslo-3-seater-sofa",
    name: "Oslo 3 Seater Sofa",
    sub: "Easy-clean oat weave",
    description:
      "Our bestselling 3 seater in a hard-wearing oat weave that shrugs off family life. Deep seats, feather-wrapped cushions and a solid hardwood frame — comfort you can sink into, built to keep its shape for years.",
    price: 649,
    wasPrice: 899,
    category: "3-seater-sofas",
    type: "three",
    fabric: "#D8CBB4",
    fabricName: "Oat weave",
    bg: "#EFE8DC",
    accent: "#B65A35",
    tag: "Save £250",
    sku: "OSL-3-OAT",
    seats: 3,
    fabricType: "Easy-clean weave",
    colourName: "Oat",
    features: [],
    rating: 4.9,
    reviewCount: 212,
    inStock: true,
    featured: true,
    details: ["Easy-clean oat weave upholstery", "Solid hardwood frame, 5-year guarantee", "Reversible seat cushions"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod-bergen-corner",
    slug: "bergen-corner-sofa",
    name: "Bergen Corner Sofa",
    sub: "L-shape · soft velvet",
    description:
      "A generous L-shaped corner sofa in plush soft velvet. Seats the whole family with room to stretch out, and the velvet catches the light beautifully. Left or right-hand chaise available.",
    price: 1149,
    category: "corner-sofas",
    type: "corner",
    fabric: "#5E7A6B",
    fabricName: "Sage velvet",
    bg: "#DCE5DA",
    accent: "#E9D9B8",
    tag: "Best seller",
    sku: "BRG-CNR-SAG",
    seats: 4,
    fabricType: "Velvet",
    colourName: "Sage",
    features: [],
    rating: 4.8,
    reviewCount: 167,
    inStock: true,
    featured: true,
    details: ["Soft-touch sage velvet", "Left or right-hand chaise", "Solid hardwood frame, 5-year guarantee"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod-lund-chair",
    slug: "lund-armchair",
    name: "Lund Armchair",
    sub: "Bouclé · 1 seater",
    description:
      "A cocooning armchair in tactile bouclé. Compact enough for a reading corner, deep enough to disappear into. Pairs beautifully with the Oslo and Malmö ranges.",
    price: 329,
    category: "armchairs",
    type: "chair",
    fabric: "#EDE5D8",
    fabricName: "Ivory bouclé",
    bg: "#E8DFD2",
    accent: "#B65A35",
    tag: "New",
    sku: "LND-ARM-IVO",
    seats: 1,
    fabricType: "Bouclé",
    colourName: "Oat",
    features: [],
    rating: 4.9,
    reviewCount: 58,
    inStock: true,
    featured: true,
    details: ["Textured ivory bouclé", "Solid hardwood frame, 5-year guarantee", "Removable seat cushion"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod-malmo-32",
    slug: "malmo-3-plus-2-set",
    name: "Malmö 3+2 Set",
    sub: "Jumbo cord · seats 5",
    description:
      "The full living room in one order: a 3 seater and matching 2 seater in cosy jumbo cord. Seats five in comfort, with the same easy-clean finish throughout.",
    price: 1299,
    wasPrice: 1599,
    category: "3-plus-2-sets",
    type: "three",
    fabric: "#8C6B57",
    fabricName: "Cognac jumbo cord",
    bg: "#F1E4D9",
    accent: "#E9D9B8",
    tag: "Save £300",
    sku: "MLM-32-COG",
    seats: 4,
    fabricType: "Jumbo cord",
    colourName: "Mink",
    features: [],
    rating: 4.8,
    reviewCount: 94,
    inStock: true,
    featured: true,
    details: ["3 seater + 2 seater in jumbo cord", "Solid hardwood frames, 5-year guarantee", "Feather-wrapped cushions"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod-visby-3",
    slug: "visby-3-seater-sofa",
    name: "Visby 3 Seater",
    sub: "Charcoal weave",
    description:
      "A tailored 3 seater in deep charcoal weave — smart, forgiving, and endlessly versatile. The easy-clean finish makes it a natural for busy households.",
    price: 599,
    category: "3-seater-sofas",
    type: "three",
    fabric: "#3F4443",
    fabricName: "Charcoal weave",
    bg: "#E8DFD2",
    accent: "#C27B5A",
    tag: "Best seller",
    sku: "VSB-3-CHA",
    seats: 3,
    fabricType: "Easy-clean weave",
    colourName: "Charcoal",
    features: [],
    rating: 4.7,
    reviewCount: 88,
    inStock: true,
    details: ["Charcoal easy-clean weave", "Solid hardwood frame, 5-year guarantee", "Reversible seat cushions"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod-aarhus-corner",
    slug: "aarhus-corner-sofa",
    name: "Aarhus Corner Sofa",
    sub: "Left or right hand",
    description:
      "A warm terracotta corner sofa that brings the whole room together. Choose a left or right-hand chaise, sink into the deep seats, and stretch out.",
    price: 1249,
    wasPrice: 1449,
    category: "corner-sofas",
    type: "corner",
    fabric: "#C27B5A",
    fabricName: "Terracotta weave",
    bg: "#F4E1D6",
    accent: "#F6F1EA",
    tag: "Save £200",
    sku: "ARH-CNR-TER",
    seats: 4,
    fabricType: "Easy-clean weave",
    colourName: "Terracotta",
    features: [],
    rating: 4.8,
    reviewCount: 61,
    inStock: true,
    details: ["Terracotta easy-clean weave", "Left or right-hand chaise", "Solid hardwood frame, 5-year guarantee"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod-dalby-2",
    slug: "dalby-2-seater-sofa",
    name: "Dalby 2 Seater",
    sub: "Navy velvet",
    description:
      "A jewel-box 2 seater in rich navy velvet. Compact footprint, full-size comfort — made for flats, snugs and statement corners.",
    price: 479,
    category: "3-seater-sofas",
    type: "three",
    fabric: "#2E3F5C",
    fabricName: "Navy velvet",
    bg: "#DCE8F3",
    accent: "#D9B8AE",
    tag: "New",
    sku: "DLB-2-NAV",
    seats: 2,
    fabricType: "Velvet",
    colourName: "Navy",
    features: [],
    rating: 4.7,
    reviewCount: 34,
    inStock: true,
    details: ["Navy soft-touch velvet", "Compact 2-seater footprint", "Solid hardwood frame, 5-year guarantee"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod-fjord-corner",
    slug: "fjord-corner-sofa",
    name: "Fjord Corner Sofa",
    sub: "Mink easy-clean",
    description:
      "A calm, contemporary corner sofa in mink easy-clean weave. Generous proportions, wipeable fabric, and a silhouette that suits any room.",
    price: 1099,
    category: "corner-sofas",
    type: "corner",
    fabric: "#8B7B6B",
    fabricName: "Mink weave",
    bg: "#EFE8DC",
    accent: "#EDE5D8",
    tag: "New",
    sku: "FJD-CNR-MNK",
    seats: 4,
    fabricType: "Easy-clean weave",
    colourName: "Mink",
    features: [],
    rating: 4.8,
    reviewCount: 27,
    inStock: true,
    details: ["Mink easy-clean weave", "Generous L-shaped footprint", "Solid hardwood frame, 5-year guarantee"],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod-nyborg-chair",
    slug: "nyborg-armchair",
    name: "Nyborg Armchair",
    sub: "Mustard cord",
    description:
      "A shot of sunshine in soft mustard jumbo cord. The Nyborg armchair is the accent piece that makes the room — deep, comfy and unapologetically cheerful.",
    price: 349,
    category: "armchairs",
    type: "chair",
    fabric: "#CFA33A",
    fabricName: "Mustard jumbo cord",
    bg: "#F6EBC9",
    accent: "#1F3A32",
    tag: "New",
    sku: "NYB-ARM-MUS",
    seats: 1,
    fabricType: "Jumbo cord",
    colourName: "Mustard",
    features: [],
    rating: 4.9,
    reviewCount: 19,
    inStock: true,
    details: ["Mustard jumbo cord", "Solid hardwood frame, 5-year guarantee", "Deep, supportive seat"],
    createdAt: now,
    updatedAt: now,
  },
];

export const seedFaqs: Faq[] = [
  { id: "faq-1", q: "Do I pay anything online?", a: "No. You place the order with your details only. Payment is made to the driver when the sofa arrives.", order: 1 },
  { id: "faq-2", q: "How can I pay the driver?", a: "Our drivers accept cash, card payments via a card machine, and bank transfer. Your driver will confirm the total with you before you pay.", order: 2 },
  { id: "faq-3", q: "What if I don't like it at the door?", a: "You can inspect the sofa before paying — check the fabric, the fit and the finish. If it isn't right, you can refuse delivery and you pay nothing.", order: 3 },
  { id: "faq-4", q: "How long does delivery take?", a: "Most sofas are delivered within 7–14 days. We call you first to agree a delivery slot that suits you.", order: 4 },
];

export const seedReviews: Review[] = [
  { id: "rev-1", quote: "The driver let us look the sofa over properly before we paid a penny. It looked even better than the pictures — we paid cash and they took the packaging away.", author: "Sarah", location: "Manchester", rating: 5, order: 1 },
  { id: "rev-2", quote: "Ordered Tuesday, phone call Wednesday to arrange the slot, sofa in the living room the following week. Paying on delivery took all the risk out of buying online.", author: "James", location: "Birmingham", rating: 5, order: 2 },
  { id: "rev-3", quote: "Really comfortable corner sofa and the velvet is gorgeous. The two-man team carried it straight upstairs to the room of our choice. Would absolutely buy again.", author: "Priya", location: "Leeds", rating: 5, order: 3 },
];

export const seedSettings: SiteSettings = {
  announcementBar: [
    "Nothing to pay online — pay on delivery",
    "Free UK delivery over £500",
    "Inspect your sofa at the door first",
  ],
  freeDeliveryThreshold: 500,
  acceptedPayments: ["cash", "card", "bank_transfer"],
  deliveryTimeText: "Most sofas are delivered within 7–14 days. We call you first to agree a delivery slot.",
  confirmationCallText: "We confirm every order by phone or text before dispatch to check your address and delivery slot.",
  refusalPolicy: "Inspect your sofa at the door before paying. If it isn't right, you can refuse delivery and you pay nothing.",
  phone: "+44 161 000 0000",
  email: "hello@sofora.example",
  address: "Sofora, Manchester, United Kingdom",
  trustpilotRating: "Excellent",
};

export const seedSteps = [
  { n: "01", t: "Order online", d: "Pick your sofa and fabric. No payment details needed." },
  { n: "02", t: "We confirm by phone", d: "A quick call or text to check your address and delivery slot." },
  { n: "03", t: "We deliver", d: "A two-person team brings it to your room of choice." },
  { n: "04", t: "Inspect, then pay", d: "Happy with it? Pay the driver by cash or card. Not right? Refuse it." },
];

export const seedWhy = [
  { t: "Pay only when you're happy", d: "See the fabric, test the seat and check the finish at your door. Then pay the driver." },
  { t: "Built to last", d: "Solid frames and a 5-year guarantee on many ranges, with easy-clean fabrics for family life." },
  { t: "Delivered to your room", d: "Free UK delivery with a two-person team. We'll call first to agree your slot." },
];
